version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-student}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    ports:
      - "8091:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

  api:
    build: ./api  
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/student"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend
    volumes:
      - ./api:/app  


  web-app:
    build: ./web_app
    ports:
      - "8090:5000"
    depends_on:
      - api
      - database
    networks:
      - frontend
    volumes:
      - ./web_app:/app

networks:
  backend:
  frontend:

volumes:
  db_data:
